import Head from "next/head";
import { chakra } from "@chakra-ui/react";
import type { NextPage } from "next";
import { Scroll } from "scrollex";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import IntroSection from "../components/sections/IntroSection";

const ScrollContainer = chakra(Scroll.Container);

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ScrollContainer>
        <IntroSection />
      </ScrollContainer>
    </>
  );
}
