import Head from "next/head";
import { chakra } from "@chakra-ui/react";
import type { NextPage } from "next";
import { Scroll } from "scrollex";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import IntroSection from "../components/sections/IntroSection";
import HeadingSection from "../components/sections/HeadingSection";
import AboutSection from "../components/sections/AboutSection";

const ScrollContainer = chakra(Scroll.Container);

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ScrollContainer height="100vh">
        <IntroSection />
        <HeadingSection heading="Hello There" />
        <AboutSection />
      </ScrollContainer>
    </>
  );
};

export default Home;
